name: frontend
description: Admin panel for managing quizzes in a full-stack Flutter app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.0.2
  go_router: ^15.1.3
  mongo_dart: ^0.10.0
  dartz: ^0.10.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^0.3.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/bgimg.jpg
    - assets/images/logoimg.jpg
    - assets/images/sidebar.png
    - assets/images/background.png
    - assets/images/ic_close.png
    - assets/images/ic_menu.png
    - assets/images/ic_user.png
    
